Vectorization
-------------
Vectorization means performing an operation on an entire Pandas Series/column at once instead of looping through every row.

In [2]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "Riya"],
    "Salary": [40000, 50000, 60000, 45000, 70000]
})

In [3]:
df["Salary"]=df["Salary"]*1.15
print(df)

    Name   Salary
0   Amit  46000.0
1  Priya  57500.0
2  Rahul  69000.0
3   Neha  51750.0
4   Riya  80500.0


In [4]:
df["Bonus"]=df["Salary"]*0.1
print(df)

    Name   Salary   Bonus
0   Amit  46000.0  4600.0
1  Priya  57500.0  5750.0
2  Rahul  69000.0  6900.0
3   Neha  51750.0  5175.0
4   Riya  80500.0  8050.0


In [5]:
df["Tax"]=df["Salary"]*0.05
print(df)

    Name   Salary   Bonus     Tax
0   Amit  46000.0  4600.0  2300.0
1  Priya  57500.0  5750.0  2875.0
2  Rahul  69000.0  6900.0  3450.0
3   Neha  51750.0  5175.0  2587.5
4   Riya  80500.0  8050.0  4025.0


memory_usage()
-------------
to check how much memory a Pandas DataFrame uses

In [6]:
df.memory_usage()

Index     132
Name       40
Salary     40
Bonus      40
Tax        40
dtype: int64

In [7]:
df.memory_usage(deep=True)

Index     132
Name      267
Salary     40
Bonus      40
Tax        40
dtype: int64

Choosing Efficient Data Types
---------------------------
Use the smallest appropriate dtype for your data to reduce memory usage and potentially improve performance.

| Data                 | Possible dtype       |
| -------------------- | -------------------- |
| Small whole numbers  | `int8`, `int16`      |
| Larger whole numbers | `int32`, `int64`     |
| Decimal values       | `float32`, `float64` |
| Repeated categories  | `category`           |
| Text                 | `string`             |


In [2]:
import pandas as pd
df = pd.DataFrame({
    "Age": [21, 24, 27, 30, 35],
    "Experience": [1, 3, 5, 7, 10],
    "Salary": [40000, 50000, 60000, 75000, 90000]
})

In [4]:
print(df.dtypes)
print(df.memory_usage(deep=True))

Age           int64
Experience    int64
Salary        int64
dtype: object
Index         132
Age            40
Experience     40
Salary         40
dtype: int64


In [8]:
df["Age"] = df["Age"].astype("int8")
df["Experience"] = df["Experience"].astype("int8")
df["Salary"] = df["Salary"].astype("int32")
print(df.dtypes)

Age            int8
Experience     int8
Salary        int32
dtype: object


| dtype   | Storage |            Approximate range |
| ------- | ------: | ---------------------------: |
| `int8`  |  1 byte |                  -128 to 127 |
| `int16` | 2 bytes |            -32,768 to 32,767 |
| `int32` | 4 bytes | ~-2.1 billion to 2.1 billion |
| `int64` | 8 bytes |             Very large range |


Category
---------
category when a column contains a limited number of repeated values.

In [12]:
df=pd.DataFrame({
    "Department":[
        "IT","HR","IT","Finance",
        "IT","HR","Finance","IT"
    ]
})


In [15]:
df["Department"]=df["Department"].astype("category")
print(df["Department"].dtype)


category


In [16]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104],
    "Name": ["Amit", "Priya", "Rahul", "Neha"]
})

salary = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104],
    "Salary": [40000, 50000, 60000, 70000]
})

In [18]:
result=pd.merge(
    employees,
    salary,
    on="Employee_ID"
)
print(result)

   Employee_ID   Name  Salary
0          101   Amit   40000
1          102  Priya   50000
2          103  Rahul   60000
3          104   Neha   70000


View
-----
A view is another way of looking at the same underlying data.

Copy
----
A copy creates independent data.

In [21]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul"],
    "Salary":[40000,50000,60000]
})
df2=df.copy()
df2["Salary"]=df2["Salary"]+5000
print(df)
print("----------------------------------")
print(df2)

    Name  Salary
0   Amit   40000
1  Priya   50000
2  Rahul   60000
----------------------------------
    Name  Salary
0   Amit   45000
1  Priya   55000
2  Rahul   65000


Convert Pandas column to NumPy array
-------------------------------------

In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha"],
    "Salary":[40000,50000,60000,45000]
})
salary_array=df["Salary"].to_numpy()
print(salary_array)

[40000 50000 60000 45000]


In [4]:
df["Salary"]=np.sqrt(df["Salary"])
print(df["Salary"])

0    3.760603
1    3.866974
2    3.956115
3    3.816380
Name: Salary, dtype: float64


In [5]:
df["Bonus"]=np.where(
    df["Salary"]>=50000,
    df["Salary"]*0.10,
    df["Salary"]*0.05
)

In [6]:
df["Bonus"]

0    0.188030
1    0.193349
2    0.197806
3    0.190819
Name: Bonus, dtype: float64

In [7]:
salary=df["Salary"].to_numpy()
salary_after_bonus=salary*1.10
df["Salary_After_Bonus"]=salary_after_bonus

In [8]:
df["Salary_After_Bonus"]

0    4.136663
1    4.253671
2    4.351726
3    4.198018
Name: Salary_After_Bonus, dtype: float64

Practice
---------

In [9]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha","Riya"],
    "Salary":[40000,55000,70000,45000,65000]
})

In [15]:
salary=df["Salary"].to_numpy()
print(salary)
salary=salary*1.10
print(salary)
df["Bonus"]=np.where(df["Salary"]>=60000,df["Salary"]*0.15,df["Salary"]*0.05)
print(df["Bonus"])

[40000 55000 70000 45000 65000]
[44000. 60500. 77000. 49500. 71500.]
0     2000.0
1     2750.0
2    10500.0
3     2250.0
4     9750.0
Name: Bonus, dtype: float64


eval()
-----
eval() allows you to perform calculations involving DataFrame columns using an expression written as a string.

In [18]:
df["Total"]=df["Salary"]+df["Bonus"]
df.eval("Total=Salary+Bonus",inplace=True)
print(df)

    Name  Salary    Bonus    Total
0   Amit   40000   2000.0  42000.0
1  Priya   55000   2750.0  57750.0
2  Rahul   70000  10500.0  80500.0
3   Neha   45000   2250.0  47250.0
4   Riya   65000   9750.0  74750.0


In [23]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahu"],
    "Salary":[40000,50000,70000],
    "Bonus":[4000,5000,7000]
})
df.eval("Total_Salary=Salary+Bonus",inplace=True)
df.eval("Net_Salary=Total_Salary-2000",inplace=True)
print(df)

    Name  Salary  Bonus  Total_Salary  Net_Salary
0   Amit   40000   4000         44000       42000
1  Priya   50000   5000         55000       53000
2   Rahu   70000   7000         77000       75000


📝 Practice
------------

In [26]:
df=pd.DataFrame({
    "Name":["Amit","Priya","Rahul","Neha","Riya"],
    "Salary":[40000,55000,70000,45000,65000],
    "Bonus":[4000,5500,10500,2250,9750]
})
df.eval("Total_salary=Salary+Bonus", inplace=True)
df.eval("After_Tax=Total_salary-(Total_salary*0.05)",inplace=True)
print(df)

    Name  Salary  Bonus  Total_salary  After_Tax
0   Amit   40000   4000         44000    41800.0
1  Priya   55000   5500         60500    57475.0
2  Rahul   70000  10500         80500    76475.0
3   Neha   45000   2250         47250    44887.5
4   Riya   65000   9750         74750    71012.5


Benchmarking
------------
Benchmarking means measuring how long code takes to execute.

In [27]:
import timeit
time=timeit.timeit(
    "sum(range(1000))",
    number=1000
)
print(time)

0.03644830000030197


In [7]:
import pandas as pd
import numpy as np
import timeit

df=pd.DataFrame({
    "Salary":np.random.randint(30000,100000,100000)
})

vectorized_time=timeit.timeit(
    "df['Salary']*1.10",
    globals=globals(),
    number=100
)
print(vectorized_time)


0.03968469999381341


In [9]:
apply_time=timeit.timeit(
    "df['Salary'].apply(lambda x:x*1.10)",
    globals=globals(),
    number=100
)
print(apply_time)

5.57277630000317


Efficient Data Loading & Memory Optimization
--------------------------------------------

🧠 Real-world workflow
-----------------------
Think:

Large CSV → Select columns → Set efficient dtypes → Load → Check memory
-----------------------------------------------------------------------

Downcasting
-----------
Downcasting means converting a numeric column from a larger dtype to a smaller dtype when the values safely fit.

Downcasting = same type, smaller size

int64 → int32 → int16 → int8
float64 → float32

📝 Practice
------------

In [11]:
import pandas as pd
df = pd.DataFrame({
    "Age": [21, 24, 27, 30, 35],
    "Experience": [1.5, 3.0, 5.5, 7.0, 10.0],
    "Salary": [40000, 50000, 60000, 75000, 90000]
})

In [13]:
print(df.dtypes)

Age             int64
Experience    float64
Salary          int64
dtype: object


In [15]:
df["Age"]=pd.to_numeric(df["Age"],downcast="integer")
df["Experience"]=pd.to_numeric(df["Experience"],downcast="float")

In [16]:
print(df.dtypes)

Age              int8
Experience    float32
Salary          int64
dtype: object


🧠 Complete memory optimization formula
-----------------------
Load less → Store efficiently → Process less → Process in batches

In Pandas:

Load less → Store efficiently → Filter early → Vectorize → Avoid unnecessary copies → Process in chunks → Measure performance